[env]
TERM="xterm-256color"

[shell]
program="/bin/zsh"

[font]
normal={family = "FiraCode Nerd Font Propo", style = "Regular"}
bold={family = "FiraCode Nerd Font Propo", style = "Bold"}

size = 15.0

[window]
dimensions = {columns = 120, lines = 35}
padding={x=16,y=4}

[mouse]
hide_when_typing=true
