[env]
TERM="xterm-256color"

[terminal.shell]
program="/bin/zsh"

[font]
normal={family = "FiraCode Nerd Font Propo", style = "Regular"}
bold={family = "FiraCode Nerd Font Propo", style = "Bold"}

size = 11.0

[window]
dimensions = {columns = 120, lines = 35}
padding={x=0,y=0}

[mouse]
hide_when_typing=true

[terminal]
