[shell]
program="/bin/zsh"

[window]
decorations="None"

[font]
normal.family={family = "FiraCode Nerd Font Propo", style = "Regular"}
bold.family={family = "FiraCode Nerd Font Propo", style = "Bold"}

size = 15.0

[mouse]
hide_when_typing=true

